name: Gerar APK Fliyer Express

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Gerar APK
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: FliyerExpress-APK
          path: app/build/outputs/apk/debug/app-debug.apk
